#%RAML 1.0
---
title: Importation Service
version: v1
types:
  ApiError: !include schema_infra_utils.json#/definitions/ApiError
  Job: !include schema_platform_kernel.json#/definitions/Job
  Importer: !include schema_platform_importation.json#/definitions/Importer
  Importers: !include schema_platform_importation.json#/definitions/Importers
  ImporterConfiguration: !include schema_platform_importation.json#/definitions/ImporterConfiguration
  ImporterConfigurations: !include schema_platform_importation.json#/definitions/ImporterConfigurations
  Document: !include schema_platform_importation.json#/definitions/Document
  Documents: !include schema_platform_importation.json#/definitions/Documents
traits: !include api_traits.raml
baseUri: https://localhost:8443/api
/services/importation:
  /importers:
    description: The collection of available data importers for the platform
    get:
      description: Gets the list of available data importers for the platform
      is: [secured, mayFail]
      responses:
        200:
          description: The list of the available data importers for the platform
          body:
            application/json:
              type: Importers
              example: |
                [
                  {
                    "type": "org.xowl.platform.services.importation.Importer",
                    "identifier": "org.xowl.platform.importers.CSVImporter",
                    "name": "CSV Importer",
                    "wizardUri": "contributions/importers/csv"
                  }
                ]
    /{importerId}:
      description: A specific data importer for the platform
      get:
        description: Gets a description of the importer
        is: [secured, mayFail, resourceAccess]
        responses:
          200:
            description: A description of the importer
            body:
              application/json:
                type: Importer
                example: |
                  {
                    "type": "org.xowl.platform.services.importation.Importer",
                    "identifier": "org.xowl.platform.importers.CSVImporter",
                    "name": "CSV Importer",
                    "wizardUri": "contributions/importers/csv"
                  }
      /configurations:
        description: The stored configurations for this importer
        get:
          description: Gets the stored configurations for this importer
          is: [secured, mayFail, resourceAccess]
          responses:
            200:
              description: The stored configurations for this importer
              body:
                application/json:
                  type: ImporterConfigurations
                  example: |
                    [
                      {
                        "type": "org.xowl.platform.services.importation.ImporterConfiguration",
                        "identifier": "http://xowl.org/platform/services/importation/ImporterConfiguration#0001",
                        "name": "My Configuration 0001",
                        "importer": "{importerId}"
                      }
                    ]
  /configurations:
    description: The collection of stored configurations for importers
    get:
      description: Gets the stored configurations for importer
      is: [secured, mayFail]
      responses:
        200:
          description: The collection of stored configurations for importers
          body:
            application/json:
              type: ImporterConfigurations
              example: |
                [
                  {
                    "type": "org.xowl.platform.services.importation.ImporterConfiguration",
                    "identifier": "http://xowl.org/platform/services/importation/ImporterConfiguration#0001",
                    "name": "My Configuration 0001",
                    "importer": "{importerId}"
                  }
                ]
    put:
      description: Stores a new configuration for an importer
      is: [secured, mayFail, resourceAccess]
      body:
        application/json:
          type: ImporterConfiguration
          example: |
            {
              "type": "org.xowl.platform.services.importation.ImporterConfiguration",
              "identifier": "http://xowl.org/platform/services/importation/ImporterConfiguration#0001",
              "name": "My Configuration 0001",
              "importer": "{importerId}"
            }
      responses:
        200:
          description: The operation succeeded
    /{configurationId}:
      description: A specific stored configuration for an importer
      get:
        description: Gets the stored configuration
        is: [secured, mayFail, resourceAccess]
        responses:
          200:
            description: The stored configuration
            body:
              application/json:
                type: ImporterConfiguration
                example: |
                  {
                    "type": "org.xowl.platform.services.importation.ImporterConfiguration",
                    "identifier": "http://xowl.org/platform/services/importation/ImporterConfiguration#0001",
                    "name": "My Configuration 0001",
                    "importer": "{importerId}"
                  }
      delete:
        description: Deletes the stored configuration
        is: [secured, mayFail, resourceAccess]
        responses:
          200:
            description: The operation succeeded
  /documents:
    description: The collection of uploaded documents
    get:
      description: Gets the list of the uploaded documents
      is: [secured, mayFail]
      responses:
        200:
          description: The list of the uploaded documents
          body:
            application/json:
              type: Documents
              example: |
                [
                  {
                    "type": "org.xowl.platform.services.importation.Document",
                    "identifier": "mydocument1",
                    "name": "Document XXX",
                    "uploadDate": "01/01/2001 10:10",
                    "uploader": "jdoe",
                    "fileName": "mydocument.csv"
                  }
                ]
    put:
      description: Uploads a new document
      is: [secured, mayFail]
      queryParameters:
        name:
          displayName: Name
          type: string
          description: The name for the uploaded document
          example: Document XXX
          required: true
        fileName:
          displayName: Original file name
          type: string
          description: The original name of the file when uploaded
          example: mydocument.csv
          required: true
      body:
        binary/octet-stream:
          description: The content of the file to upload
      responses:
        200:
          description: The description of the uploaded document
          body:
            application/json:
              type: Document
              example: |
                {
                  "type": "org.xowl.platform.services.importation.Document",
                  "identifier": "mydocument1",
                  "name": "Document XXX",
                  "uploadDate": "01/01/2001 10:10",
                  "uploader": "jdoe",
                  "fileName": "mydocument.csv"
                }
    /{documentId}:
      description: A specific uploaded document
      get:
        description: Gets a description of the document
        is: [secured, mayFail, resourceAccess]
        responses:
          200:
            description: The description of the document
            body:
              application/json:
                type: Document
                example: |
                  {
                    "type": "org.xowl.platform.services.importation.Document",
                    "identifier": "mydocument1",
                    "name": "Document XXX",
                    "uploadDate": "01/01/2001 10:10",
                    "uploader": "jdoe",
                    "fileName": "mydocument.csv"
                  }
      delete:
        description: Deletes the document
        is: [secured, mayFail, resourceAccess]
        responses:
          200:
            description: The operation succeeded
      /preview:
        description: Action to request a preview of the data that would be imported from the document
        post:
          description: Requests a preview of the data that would be imported from the document
          is: [secured, mayFail, resourceAccess]
          queryParameters:
            configuration:
              displayName: Configuration
              type: string
              description: The identifier of the the stored configuration to use
              example: http://xowl.org/platform/services/importation/ImporterConfiguration#0001
              required: false
          body:
            application/json:
              description: The configuration for the importer
              type: ImporterConfiguration
              example: |
                {
                  "type": "org.xowl.platform.services.importation.ImporterConfiguration",
                  "identifier": "http://xowl.org/platform/services/importation/ImporterConfiguration#0001",
                  "name": "My Configuration 0001",
                  "importer": "{importerId}"
                }
          responses:
            200:
              description: The preview of the data that would be imported from the document
              body:
               application/json:
      /import:
        description: Action to launch the importation of data from the document
        post:
          description: Requests to launch the importation of data from the document
          is: [secured, mayFail, resourceAccess]
          queryParameters:
            configuration:
              displayName: Configuration
              type: string
              description: The identifier of the the stored configuration to use
              example: http://xowl.org/platform/services/importation/ImporterConfiguration#0001
              required: false
            name:
              displayName: Artifact Name
              type: string
              description: The name of the artifact to produce
              example: My Artifact
              required: true
            base:
              displayName: Artifact Base URI
              type: string
              description: The base family URI for the artifact
              example: http://xowl.org/artifacts/base
              required: true
            version:
              displayName: Artifact Version
              type: string
              description: The version for the artifact
              example: v1
              required: true
            archetype:
              displayName: Artifact Archetype
              type: string
              description: The archetype for the artifact
              example: org.xowl.platform.kernel.artifacts.ArtifactArchetypeFree
              required: true
            superseded:
              displayName: Superseded Artifact
              type: string
              description: The identifier of the artifact superseded by this one
              example: My Artifact
              required: false
          body:
            application/json:
              description: The configuration for the importer
              type: ImporterConfiguration
              example: |
                {
                  "type": "org.xowl.platform.services.importation.ImporterConfiguration",
                  "identifier": "http://xowl.org/platform/services/importation/ImporterConfiguration#0001",
                  "name": "My Configuration 0001",
                  "importer": "{importerId}"
                }
          responses:
            200:
              description: The job that imports the document
              body:
                application/json:
                  type: Job
                  example: |
                    {
                      "type": "org.xowl.platform.kernel.jobs.Job",
                      "identifier": "job1",
                      "name": "Import Document XXX",
                      "jobType": "org.xowl.platform.services.importation.ImportationJob",
                      "owner": {
                        "type": "org.xowl.platform.kernel.platform.PlatformUser",
                        "identifier": "jdoe",
                        "name": "Jane Doe"
                      },
                      "status": "Running",
                      "timeScheduled": "01/01/2001 10:10",
                      "timeRun": "01/01/2001 10:10",
                      "timeCompleted": "",
                      "completionRate": "0.5",
                      "payload": "document1",
                      "result": {}
                    }