FROM tomcat:8.0-jre8
MAINTAINER Laurent Wouters <lwouters@xowl.org>
LABEL description "Docker image for the xOWL federation platform"
VOLUME ["/config"]
COPY target/xowl-activiti-*.war /usr/local/tomcat/webapps/activiti.war