#%RAML 1.0
---
title: Business Directory Service
version: v1
types:
  ApiError: !include schema_infra_utils.json#/definitions/ApiError
  ArtifactArchetype: !include schema_platform_kernel.json#/definitions/ArtifactArchetype
  ArtifactArchetypes: !include schema_platform_kernel.json#/definitions/ArtifactArchetypes
  ArtifactSchema: !include schema_platform_kernel.json#/definitions/ArtifactSchema
  ArtifactSchemas: !include schema_platform_kernel.json#/definitions/ArtifactSchemas
traits: !include api_traits.raml
baseUri: https://localhost:8443/api
/kernel/business:
  /archetypes:
    description: The artifact archetypes registered on this platform
    get:
      description: Gets the artifact archetypes registered on this platform
      is: [secured, mayFail]
      responses:
        200:
          description: The artifacts archetypes
          body:
            application/json:
              type: ArtifactArchetypes
              example: |
                [
                  {
                    "type": "org.xowl.platform.kernel.artifacts.ArtifactArchetype",
                    "identifier": "org.xowl.platform.kernel.artifacts.FreeArtifactArchetype",
                    "name": "Free Artifact Archetype",
                    "description": "An archetype for artifacts that follow no specific schema.",
                    "schema": ""
                  }
                ]
    /{archetypeId}:
      description: Represents a specific archetype on this platform
      get:
        description: Gets the description of an archetype
        is: [secured, mayFail, resourceAccess]
        responses:
          200:
            description: The description of the artifact
            body:
              application/json:
                type: ArtifactArchetype
                example: |
                  {
                    "type": "org.xowl.platform.kernel.artifacts.ArtifactArchetype",
                    "identifier": "org.xowl.platform.kernel.artifacts.FreeArtifactArchetype",
                    "name": "Free Artifact Archetype",
                    "description": "An archetype for artifacts that follow no specific schema.",
                    "schema": ""
                  }
  /schemas:
    description: The business schemas registered on this platform
    get:
      description: Gets the business schemas registered on this platform
      is: [secured, mayFail]
      responses:
        200:
          description: The business schemas
          body:
            application/json:
              type: ArtifactSchemas
              example: |
                [
                  {
                    "type": "org.xowl.platform.kernel.artifacts.BusinessSchema",
                    "identifier": "http://xowl.org/platform/kernel",
                    "name": "Kernel Schema",
                    "classes": [
                      {
                        "identifier": "http://xowl.org/platform/kernel#Class1",
                        "name": "Class 1"
                      }
                    ],
                    "datatypes": [
                      {
                        "identifier": "http://xowl.org/platform/kernel#weirdString",
                        "name": "Weird String"
                      }
                    ],
                    "objectProperties": [
                      {
                        "identifier": "http://xowl.org/platform/kernel#owner",
                        "name": "Owner"
                      }
                    ],
                    "dataProperties": [
                      {
                        "identifier": "http://xowl.org/platform/kernel#name",
                        "name": "Name"
                      }
                    ],
                    "individuals": [
                      {
                        "identifier": "http://xowl.org/platform/kernel#Subject1",
                        "name": "Subject 1"
                      }
                    ]
                  }
                ]
    /{schemaId}:
      description: Represents a specific business schema on this platform
      get:
        description: Gets the description of a business schema
        is: [secured, mayFail, resourceAccess]
        responses:
          200:
            description: The description of the business schema
            body:
              application/json:
                type: ArtifactSchema
                example: |
                  {
                    "type": "org.xowl.platform.kernel.artifacts.BusinessSchema",
                    "identifier": "http://xowl.org/platform/kernel",
                    "name": "Kernel Schema",
                    "classes": [
                      {
                        "identifier": "http://xowl.org/platform/kernel#Class1",
                        "name": "Class 1"
                      }
                    ],
                    "datatypes": [
                      {
                        "identifier": "http://xowl.org/platform/kernel#weirdString",
                        "name": "Weird String"
                      }
                    ],
                    "objectProperties": [
                      {
                        "identifier": "http://xowl.org/platform/kernel#owner",
                        "name": "Owner"
                      }
                    ],
                    "dataProperties": [
                      {
                        "identifier": "http://xowl.org/platform/kernel#name",
                        "name": "Name"
                      }
                    ],
                    "individuals": [
                      {
                        "identifier": "http://xowl.org/platform/kernel#Subject1",
                        "name": "Subject 1"
                      }
                    ]
                  }