#%RAML 1.0
---
title: Consistency Service
version: v1
types:
  ApiError: !include schema_infra_utils.json#/definitions/ApiError
  Inconsistencies: !include schema_platform_consistency.json#/definitions/Inconsistencies
  ReasoningRule: !include schema_platform_consistency.json#/definitions/ReasoningRule
  ReasoningRules: !include schema_platform_consistency.json#/definitions/ReasoningRules
  ConsistencyConstraint: !include schema_platform_consistency.json#/definitions/ConsistencyConstraint
  ConsistencyConstraints: !include schema_platform_consistency.json#/definitions/ConsistencyConstraints
traits: !include api_traits.raml
baseUri: https://localhost:8443/api
/services/consistency:
  /inconsistencies:
    description: The collection of the current inconsistencies in the live data on the platform
    get:
      description: Gets the list of the current inconsistencies in the live data on the platform
      is: [secured, mayFail]
      responses:
        200:
          description: The list of the current inconsistencies in the live data
          body:
            application/json:
              type: Inconsistencies
              example: |
                [
                  {
                    "type": "org.xowl.platform.services.consistency.Inconsistency",
                    "identifier": "http://xowl.org/inconsistency/XXXX",
                    "message": "The object ?x has property ?p but not ?q.",
                    "constraintId": "http://xowl.org/constraints/constraint1",
                    "constraintName": "Consistency Constraint 1",
                    "antecedents": {
                      "x": {
                        "type": "uri",
                        "value": "http://xowl.org/data/entity1"
                      },
                      "p": {
                        "type": "uri",
                        "value": "http://xowl.org/schemas/property1"
                      },
                      "q": {
                        "type": "uri",
                        "value": "http://xowl.org/schemas/property2"
                      }
                    }
                  }
                ]
  /rules:
    description: The collection of reasoning rules on the platform
    get:
      description: Gets the list of reasoning rules on the platform
      is: [secured, mayFail]
      responses:
        200:
          description: The list of the reasoning rules on the platform
          body:
            application/json:
              type: ReasoningRules
              example: |
                [
                  {
                    "type": "org.xowl.platform.services.consistency.ReasoningRule",
                    "identifier": "http://xowl.org/rules/rule1",
                    "name": "Rule 1",
                    "definition": "RULE xowl:rule1 { ?x ?p ?y . } => { ?x ?q ?y . }",
                    "isActive": true
                  }
                ]
    put:
      description: Creates a new reasoning rule
      is: [secured, mayFail]
      queryParameters:
        name:
          displayName: Rule name
          type: string
          description: The human-readable name for the rule
          example: Rule 1
          required: true
      body:
        text/plain:
          description: The definition for the rule
          example: |
            RULE xowl:rule1 { ?x ?p ?y . } => { ?x ?q ?y . }
      responses:
        200:
          description: The description of the created rule
          body:
            application/json:
              type: ReasoningRule
              example: |
                {
                  "type": "org.xowl.platform.services.consistency.ReasoningRule",
                  "identifier": "http://xowl.org/rules/rule1",
                  "name": "Rule 1",
                  "definition": "RULE xowl:rule1 { ?x ?p ?y . } => { ?x ?q ?y . }",
                  "isActive": true
                }
    /{ruleId}:
      description: Represents a specific reasoning rule on the platform
      get:
        description: Gets the description of the reasoning rule
        is: [secured, mayFail, resourceAccess]
        responses:
          200:
            description: The description of the reasoning rule
            body:
              application/json:
                type: ReasoningRule
                example: |
                  {
                    "type": "org.xowl.platform.services.consistency.ReasoningRule",
                    "identifier": "http://xowl.org/rules/rule1",
                    "name": "Rule 1",
                    "definition": "RULE xowl:rule1 { ?x ?p ?y . } => { ?x ?q ?y . }",
                    "isActive": true
                  }
      put:
        description: Add the reasoning rule
        is: [secured, mayFail, resourceAccess]
        body:
          application/json:
            type: ReasoningRule
            example: |
              {
                "type": "org.xowl.platform.services.consistency.ReasoningRule",
                "identifier": "http://xowl.org/rules/rule1",
                "name": "Rule 1",
                "definition": "RULE xowl:rule1 { ?x ?p ?y . } => { ?x ?q ?y . }",
                "isActive": true
              }
        responses:
          200:
            description: The description of the reasoning rule
            body:
              application/json:
                type: ReasoningRule
                example: |
                  {
                    "type": "org.xowl.platform.services.consistency.ReasoningRule",
                    "identifier": "http://xowl.org/rules/rule1",
                    "name": "Rule 1",
                    "definition": "RULE xowl:rule1 { ?x ?p ?y . } => { ?x ?q ?y . }",
                    "isActive": true
                  }
      delete:
        description: Deletes the reasoning rule
        is: [secured, mayFail, resourceAccess]
        responses:
          200:
            description: The operation succeeded
      /activate:
        description: Action to activate the reasoning rule
        post:
          description: Activates the reasoning rule
          is: [secured, mayFail, resourceAccess]
          responses:
            200:
              description: The operation succeeded
      /deactivate:
        description: Action to de-activate the reasoning rule
        post:
          description: De-activates the reasoning rule
          is: [secured, mayFail, resourceAccess]
          responses:
            200:
              description: The operation succeeded
  /constraints:
    description: The collection of consistency constraints on the platform
    get:
      description: Gets the list of consistency constraints on the platform
      is: [secured, mayFail]
      responses:
        200:
          description: The list of the consistency constraints on the platform
          body:
            application/json:
              type: ConsistencyConstraints
              example: |
                [
                  {
                    "type": "org.xowl.platform.services.consistency.ConsistencyConstraint",
                    "identifier": "http://xowl.org/constraints/constraint1",
                    "name": "Constraint 1",
                    "definition": "...",
                    "isActive": true
                  }
                ]
    put:
      description: Creates a new consistency constraint
      is: [secured, mayFail]
      queryParameters:
        name:
          displayName: Rule name
          type: string
          description: The human-readable name for the constraint
          example: Rule 1
          required: true
        message:
          displayName: Message
          type: string
          description: The template message that will be displayed for inconsistencies produced by this constraint
          example: The object ?x has property ?p but not ?q.
          required: true
        prefixes:
          displayName: Prefixes
          type: string
          description: The URI prefixes used for the constraint definition
          example: |
            PREFIX kernel: <http://xowl.org/platform/schemas/kernel#>
          required: true
        antecedents:
          displayName: Antecedents
          type: string
          description: The conditions for the constraint
          example: |
            ?x ?p ?y
            NOT (?x ?q ?z)
          required: true
        guard:
          displayName: Guard
          type: string
          description: An optional guard as a Clojure expression for the constraint
          example: |
            (nil? (myOperation stuff))
          required: false
      responses:
        200:
          description: The description of the created constraint
          body:
            application/json:
              type: ConsistencyConstraint
              example: |
                {
                  "type": "org.xowl.platform.services.consistency.ConsistencyConstraint",
                  "identifier": "http://xowl.org/constraints/constraint1",
                  "name": "Constraint 1",
                  "definition": "...",
                  "isActive": true
                }
    /{constraintId}:
      description: Represents a specific consistency constraint on the platform
      get:
        description: Gets the description of the consistency constraint
        is: [secured, mayFail, resourceAccess]
        responses:
          200:
            description: The description of the consistency constraint
            body:
              application/json:
                type: ConsistencyConstraint
                example: |
                  {
                    "type": "org.xowl.platform.services.consistency.ConsistencyConstraint",
                    "identifier": "http://xowl.org/constraints/constraint1",
                    "name": "Constraint 1",
                    "definition": "...",
                    "isActive": true
                  }
      put:
        description: Add the consistency constraint
        is: [secured, mayFail, resourceAccess]
        body:
          application/json:
            type: ConsistencyConstraint
            example: |
              {
                "type": "org.xowl.platform.services.consistency.ConsistencyConstraint",
                "identifier": "http://xowl.org/constraints/constraint1",
                "name": "Constraint 1",
                "definition": "...",
                "isActive": true
              }
        responses:
          200:
            description: The description of the consistency constraint
            body:
              application/json:
                type: ConsistencyConstraint
                example: |
                  {
                    "type": "org.xowl.platform.services.consistency.ConsistencyConstraint",
                    "identifier": "http://xowl.org/constraints/constraint1",
                    "name": "Constraint 1",
                    "definition": "...",
                    "isActive": true
                  }
      delete:
        description: Deletes the consistency constraint
        is: [secured, mayFail, resourceAccess]
        responses:
          200:
            description: The operation succeeded
      /activate:
        description: Action to activate the consistency constraint
        post:
          description: Activates the consistency constraint
          is: [secured, mayFail, resourceAccess]
          responses:
            200:
              description: The operation succeeded
      /deactivate:
        description: Action to de-activate the consistency constraint
        post:
          description: De-activates the consistency constraint
          is: [secured, mayFail, resourceAccess]
          responses:
            200:
              description: The operation succeeded