#%RAML 1.0
---
title: Platform Management Service
version: v1
types:
  ApiError: !include schema_infra_utils.json#/definitions/ApiError
  OSGiBundle: !include schema_platform_kernel.json#/definitions/OSGiBundle
  OSGiBundles: !include schema_platform_kernel.json#/definitions/OSGiBundles
  OSGiImplementation: !include schema_platform_kernel.json#/definitions/OSGiImplementation
traits: !include api_traits.raml
baseUri: https://localhost:8443/api
/kernel/platform:
  description: Represents the platform implementation
  get:
    description: Gets the description of the platform implementation
    is: [secured, mayFail]
    responses:
      200:
        description: The description of the platform implementation
        body:
          application/json:
            schema: OSGiImplementation
            example: |
              {
                "type": "org.xowl.platform.kernel.platform.OSGiImplementation",
                "identifier": "impl1",
                "name": "OSGi Implementation Name"
              }
  /bundles:
    description: The list of the bundles deployed on this platform
    get:
      description: Gets the list of the bundles deployed on this platform
      is: [secured, mayFail]
      responses:
        200:
          description: The list of the bundles deployed on this platform
          body:
            application/json:
              schema: OSGiBundles
              example: |
                [
                  {
                    "type": "org.xowl.platform.kernel.platform.OSGiBundle",
                    "identifier": "com.corporation.product.xxx",
                    "name": "Bundle XXX",
                    "description": "The description for this bundle",
                    "vendor": "Corporation X",
                    "version": "1.0.0",
                    "state": "ACTIVE"
                  }
                ]
  /shutdown:
    description: Action to shut down the platform
    post:
      description: Shuts down this platform
      is: [secured, mayFail]
      responses:
        200:
          description: The operation succeeeded
  /restart:
    description: Action to restart the platform
    post:
      description: Restarts this platform
      is: [secured, mayFail]
      responses:
        200:
          description: The operation succeeeded