#%RAML 1.0
---
title: Bots Management Service
version: v1
types:
  ApiError: !include schema_infra_utils.json#/definitions/ApiError
  LogMessages: !include schema_platform_kernel.json#/definitions/LogMessages
  Bot: !include schema_platform_community.json#/definitions/Bot
  Bots: !include schema_platform_community.json#/definitions/Bots
traits: !include api_traits.raml
baseUri: https://localhost:8443/api
/services/community/bots:
  description: Collection of the bots on the platform
  get:
    description: Gets the list of the bots running on the platform
    is: [secured, mayFail]
    responses:
      200:
        description: The list of the bots running on the platform
        body:
          application/json:
            type: Bots
            example: |
              [
                {
                  "type": "org.xowl.platform.services.community.bots.Bot",
                  "identifier": "bender",
                  "name": "Bender",
                  "botType": "org.xowl.platform.kernel.bots.Bender",
                  "wakeupOnStartup": true,
                  "status": "Awake"
                }
              ]
  /{botId}:
    description: Represents a bot running by the platform
    get:
      description: Gets the description of the bot
      is: [secured, mayFail, resourceAccess]
      responses:
        200:
          description: The description of the bot
          body:
            application/json:
              type: Bot
              example: |
                {
                  "type": "org.xowl.platform.services.community.bots.Bot",
                  "identifier": "bender",
                  "name": "Bender",
                  "botType": "org.xowl.platform.kernel.bots.Bender",
                  "wakeupOnStartup": true,
                  "status": "Awake"
                }
    /messages:
      description: The messages from the bot
      get:
        description: Gets the messages from the bot
        is: [secured, mayFail, resourceAccess]
        responses:
          200:
            description: The messages from the bot
            body:
              application/json:
                type: LogMessages
                example: |
                  [
                    {
                      "type": "org.xowl.platform.kernel.platform.PlatformLogMessage",
                      "level": "INFO",
                      "date": "01/01/2001 10:10",
                      "content": "This is a message"
                    }
                  ]
    /wakeup:
      description: Action to wake the bot up
      post:
        description: Attemps to wake up the bot
        is: [secured, mayFail, resourceAccess]
        responses:
          200:
            description: The operation succeeded
    /putToSleep:
      description: Action to put the bot to sleep
      post:
        description: Attemps to put the bot to sleep
        is: [secured, mayFail, resourceAccess]
        responses:
          200:
            description: The operation succeeded